name: Nightly Build

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.9'

jobs:
  nightly-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [x64, arm64]
        exclude:
          # Exclude ARM64 on Ubuntu (not commonly used)
          - os: ubuntu-latest
            arch: arm64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libgtk-3-dev libx11-xcb-dev libxss1 libgconf-2-4
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Node.js dependencies
      run: |
        npm install
        npm rebuild
        
    - name: Build Python backend
      run: npm run python-build
      
    - name: Build React frontend
      run: npm run react-build
      
    - name: Build Electron main process
      run: tsc -p tsconfig.electronMain.json
      
    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: |
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          cross-env npm_config_arch=arm64 ELECTRON_BUILDER_ARCH=arm64 electron-builder --mac --arm64 --dir
        else
          cross-env npm_config_arch=x64 ELECTRON_BUILDER_ARCH=x64 electron-builder --mac --x64 --dir
        fi
        
    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: |
        if ("${{ matrix.arch }}" -eq "arm64") {
          $env:npm_config_arch="arm64"
          $env:ELECTRON_BUILDER_ARCH="arm64"
          npx electron-builder --win --arm64 --dir
        } else {
          $env:npm_config_arch="x64"
          $env:ELECTRON_BUILDER_ARCH="x64"
          npx electron-builder --win --x64 --dir
        }
        
    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        npx electron-builder --linux --x64 --dir
        
    - name: Upload nightly artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nightly-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          dist/mac-${{ matrix.arch }}/${{ matrix.os == 'macos-latest' }}
          dist/win-${{ matrix.arch }}/${{ matrix.os == 'windows-latest' }}
          dist/linux-unpacked/${{ matrix.os == 'ubuntu-latest' }}
        retention-days: 7
